# Generated by Django 3.1.7 on 2021-03-23 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortened',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('date_expiration', models.DateTimeField(default=datetime.datetime(2021, 3, 30, 16, 53, 0, 676070, tzinfo=utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
